const levelSettings = {
  0: {
    "mainCardElementCount": 0,
    "cardElementCount": 0,
    "matchingElementCount": 0,
    "showFlashcard": false,
  },
  1: {
    "mainCardElementCount": 1,
    "cardElementCount": 1,
    "matchingElementCount": 1,
    "showFlashcard": true,
    "text": "Let's start easy! Each correct card will have 1 matching symbol",
    "img": './flashcardMascot.png'
  },
  2: {
    "mainCardElementCount": 1,
    "cardElementCount": 1,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  3: {
    "mainCardElementCount": 2,
    "cardElementCount": 1,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  4: {
    "mainCardElementCount": 2,
    "cardElementCount": 1,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  5: {
    "mainCardElementCount": 2,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  6: {
    "mainCardElementCount": 2,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false
  },
  7: {
    "mainCardElementCount": 2,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  8: {
    "mainCardElementCount": 2,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  9: {
    "mainCardElementCount": 3,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  10: {
    "mainCardElementCount": 3,
    "cardElementCount": 2,
    "matchingElementCount": 1,
    "showFlashcard": false,
  },
  11: {
    "mainCardElementCount": 3,
    "cardElementCount": 3,
    "matchingElementCount": 2,
    "showFlashcard": true,
    "text": "You're quite good! From here on, each correct card will have 2 matching symbols",
    "img": "./assets/flashcardMascot.png"
  },
  12: {
    "mainCardElementCount": 3,
    "cardElementCount": 3,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  13: {
    "mainCardElementCount": 3,
    "cardElementCount": 3,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  14: {
    "mainCardElementCount": 4,
    "cardElementCount": 3,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  15: {
    "mainCardElementCount": 4,
    "cardElementCount": 3,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  16: {
    "mainCardElementCount": 4,
    "cardElementCount": 4,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  17: {
    "mainCardElementCount": 4,
    "cardElementCount": 4,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  18: {
    "mainCardElementCount": 4,
    "cardElementCount": 4,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  19: {
    "mainCardElementCount": 5,
    "cardElementCount": 4,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  20: {
    "mainCardElementCount": 5,
    "cardElementCount": 4,
    "matchingElementCount": 2,
    "showFlashcard": false,
  },
  21: {
    "mainCardElementCount": 5,
    "cardElementCount": 4,
    "matchingElementCount": 3,
    "showFlashcard": true,
    "text": "Let's turn up a notch! From here on, each correct card will have 3 matching symbols",
    "img": "./assets/flashcardMascot.png"
  },
  22: {
    "mainCardElementCount": 5,
    "cardElementCount": 4,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  23: {
    "mainCardElementCount": 5,
    "cardElementCount": 5,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  24: {
    "mainCardElementCount": 5,
    "cardElementCount": 5,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  25: {
    "mainCardElementCount": 5,
    "cardElementCount": 5,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  26: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  27: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  28: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  29: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  30: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  31: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": true,
    "text": "Oh! You're quite good! Each correct card will still have 3 matching elements, but watch out for even more similar colors",
    "img": "./assets/flashcardMascot.png"
  },
  32: {
    "mainCardElementCount": 6,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  33: {
    "mainCardElementCount": 7,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  34: {
    "mainCardElementCount": 7,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  35: {
    "mainCardElementCount": 7,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  36: {
    "mainCardElementCount": 7,
    "cardElementCount": 6,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  37: {
    "mainCardElementCount": 7,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  38: {
    "mainCardElementCount": 7,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  39: {
    "mainCardElementCount": 7,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  40: {
    "mainCardElementCount": 7,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  41: {
    "mainCardElementCount": 7,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  42: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  43: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  44: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  45: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": false,
  },
  46: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 3,
    "showFlashcard": true,
    "text": "Here's a good challenge for ya! Each correct card will now have 4 matching elements. Watch out for EVEN more similar colors",
    "img": "./assets/flashcardMascot.png"  },
  47: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  48: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  49: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  50: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  51: {
    "mainCardElementCount": 8,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  52: {
    "mainCardElementCount": 9,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  53: {
    "mainCardElementCount": 9,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  54: {
    "mainCardElementCount": 9,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  55: {
    "mainCardElementCount": 9,
    "cardElementCount": 7,
    "matchingElementCount": 4,
    "showFlashcard": false,
  },
  56: {
    "mainCardElementCount": 9,
    "cardElementCount": 9,
    "matchingElementCount": 4,
    "showFlashcard": true,
    "text": "Final level coming up, you've almost beaten the game!",
    "img": "./assets/flashcardMascot.png"  },
};

export default levelSettings;